### PR TITLE
curated list of libraries

### PR DESCRIPTION
**Pull request by FND**
this replaces the widgets page, which never seemed quite right

caveats:
- I'm not sure the current selection provides a sufficiently broad overview - anything else worth adding?
- for the moment, I refrained from adding any kind of search or filtering functionality - browsers' full-text search is just fine for that, at least while the list is still relatively small
- styling is pretty crude - perhaps @rstrangh and/or @mechanoid can improve this a little?

roca

### CODE REVIEW

**Comment by rstrangh** [comment]
Looks fine to me, but the container is definitely too wide for such small amounts of text. Try to wrap that list in a container that is 6-7 columns wide. That should improve legibility a lot.

**Comment by FND** [comment]
> Try to wrap that list in a container that is 6-7 columns wide.

That's gonna be tricky because the source is Markdown (:wave: Heydon) and while I'm using Sass here, regular CSS is used for Bootstrap (v2) - so I can't just mix in the grid classes.

**Comment by stilkov** [comment]
Do you want me to merge this as is or change something first?

**Comment by FND** [comment]
In the spirit of releasing early and often, let's merge it now. Hopefully that won't lead to the remaining issues being forgotten.

**Pull request merged**
